"""Dialectic Knowledge System (DKS) — public API.

DKS is the closed-loop dialectic runtime that turns Tessellum's typed
substrate into a learning knowledge system. Each cycle takes an
observation, generates arguments from N perspectives, detects
disagreement (pairwise contradicts edges), captures a counter-argument
naming the broken Toulmin component, discovers a pattern, and emits
revised warrants — depositing a Folgezettel subtree per closed loop.

See ``thought_dks_design_synthesis`` (FZ 2a) + ``thought_dks_fz_integration``
(FZ 2a1) in the seed vault for the typed ontology + spatial mapping.

DKS uses the Composer LLM-backend abstractions
(:class:`tessellum.composer.MockBackend` /
:class:`tessellum.composer.AnthropicBackend`) but is otherwise an
independent module — peer to :mod:`tessellum.composer` (the contract-
pipeline executor), :mod:`tessellum.retrieval` (the read side), and
:mod:`tessellum.indexer` (the write-side substrate). Built on
Composer primitives; not owned by it.

Public-API capability map:

  - **Core cycle** — :class:`DKSCycle`, :class:`DKSRunner`,
    :func:`allocate_cycle_fz`, the seven component-output dataclasses.
  - **Confidence gating** — :class:`ConstantConfidence` /
    :class:`CalibratedConfidence` + :func:`decide_escalation`.
  - **Multi-perspective + Dung labelling** — N-argument support on
    :class:`DKSCycle` via the ``perspectives`` kwarg, plus the
    :class:`DungAF` / :func:`grounded_labelling` standalone module.
  - **Meta-DKS** — schema-mutation runtime under
    :mod:`tessellum.dks.meta`.
  - **Telemetry** — warrant history, silent-failure observability,
    multi-revision authoring.
  - **The query-time protocol** — a *read* path beside the authoring
    cycle, which it does not replace: derived-claim identity
    (:mod:`~tessellum.dks.claim_identity`), the entity registry and its
    resolver (:mod:`~tessellum.dks.entity_registry`,
    :mod:`~tessellum.dks.resolve_entity`), the computed status over the
    attack relation (:mod:`~tessellum.dks.status`) with the separate
    support-dependency validator that a computed label does *not*
    establish (:mod:`~tessellum.dks.support_dependency`), the three-call
    memory boundary (:mod:`~tessellum.dks.memory_port`), bounded reach
    (:mod:`~tessellum.dks.reach`), the memory tiers
    (:mod:`~tessellum.dks.memory_tiers`), the three-way query decision
    (:mod:`~tessellum.dks.query_protocol`), and the demotion /
    consolidation gates (:mod:`~tessellum.dks.demotion`,
    :mod:`~tessellum.dks.consolidation`). **Every one of these is pure
    and additive**: no existing code path reaches them unless a caller
    opts in by name — a new CLI flag, a new MCP tool, a non-default
    ``claim_id_scheme``, a registered ``dks_query`` capability — and
    every gate they add stays default-OFF until the plan's own A/Bs are
    run.

Re-exports below are the *package* API — the names a caller reaches for.
Each module's full surface (per-reason string constants, internal
thresholds, tokenisers) stays available at ``tessellum.dks.<module>``
rather than being flattened up here.
"""

from tessellum.dks.core import (
    # Type aliases
    CounterStrength,
    CycleMode,
    ToulminComponent,
    WarrantChangeKind,
    # Component-output dataclasses
    DKSArgument,
    DKSContradicts,
    DKSCounterArgument,
    DKSCycleResult,
    DKSObservation,
    DKSPattern,
    DKSRuleRevision,
    DKSWarrant,
    # Multi-cycle
    DKSRunResult,
    WarrantChange,
    # Allocator
    allocate_cycle_fz,
    # Provenance (P1)
    temporal_holdout_valid,
    # Runtime
    DKSCycle,
    DKSRunner,
    # Helpers
    aggregate_warrant_changes,
)
from tessellum.dks.capability import (
    # P2 (b1a) — the DKS↔runtime seam (Ports & Adapters)
    Capability,
    CapabilityEffect,
    CapabilityResult,
    DKSCandidate,
    DKSExecutor,
    adapt_cycle_result,
    adapt_run_result,
)
from tessellum.dks.compiler import (
    # P3 — deterministic DKSCycleResult → NoteIntentGraph (reuse substrate)
    DKSNoteCompiler,
)
from tessellum.dks.validation import (
    # P4 (b3a) — claim-type router feeding the shipped conformal gate
    ClaimType,
    ClaimTypeRouter,
    classify_claim,
    temporal_holdout_scorer,
    validate_claims,
)
from tessellum.dks.autonomy import (
    # P5 (b2a + b6a) — outer control plane: frontier + VOI stop + authority
    AuthorityLadder,
    AuthorityLadderError,
    EpistemicObligation,
    InquiryFrontier,
    StopDecision,
    run_bounded_inquiry,
    voi_stop_decision,
)
from tessellum.dks.ontology import (
    # P6 (b7a) — ECS four-axis separation (role / move / relation / state)
    AcceptanceVerdict,
    BBContract,
    DKS_MOVE_ALGEBRA,
    InquiryMove,
    acceptance_from_labelling,
    plan_move,
)
from tessellum.dks.elevation import (
    # P7 (b4a + contract) — maturity profile, validator-issued certificate,
    # V(q), and the anti-hacking move-ranker (orders only, never commits)
    CertificateError,
    DeepUnderstandingCertificate,
    MaturityProfile,
    MoveRanker,
    QuestionValue,
    RankerAuthorityError,
    RewardInputs,
    issue_certificate,
    move_reward,
    rank_questions,
    revoke,
)
from tessellum.dks.retrieval_client import (
    # P-side retrieval client (warrant-grounding evidence fetch), plus the
    # bounded link expansion QP7's reach walks. Still read-only: there is
    # no index/update/delete surface on this port.
    DEFAULT_EXPANSION_K,
    MAX_EXPANSION_HOPS,
    LinkNeighbour,
    RetrievalClient,
    RetrievalHit,
)
from tessellum.dks.confidence import (
    # Confidence gating
    DEFAULT_CONFIDENCE_THRESHOLD,
    ConstantConfidence,
    DKSConfidenceModel,
    EscalationDecision,
    decide_escalation,
    # Learned confidence + calibration
    DEFAULT_RECENCY_HALFLIFE_CYCLES,
    DEFAULT_TARGET_FALSE_GATE_RATE,
    CalibratedConfidence,
    CalibrationResult,
    calibrate_from_traces,
)
from tessellum.dks.persistence import (
    # Warrant persistence
    HistoryEntry,
    WarrantHistory,
    WarrantRegistry,
    load_warrants_from_vault,
)
from tessellum.dks.fsm import (
    # FSM dispatcher over the BB schema
    BBPath,
    BBPathStep,
    DKSStateMachine,
    TransitionHandler,
)
from tessellum.dks.dung import (
    # Dung abstract argumentation framework + grounded semantics
    DungAF,
    DungLabel,
    grounded_extension,
    grounded_labelling,
)
from tessellum.dks.claim_identity import (
    # QP0 — derived-claim identity: THREE identities, not one. An evidence
    # occurrence is a located string at a source version; a proposition
    # version is what feedback and recurrence key on; a derivation event
    # connects a premise set to a proposition version at an episode. The
    # cross-span `fact_id` layer stays specified-not-built, and the merge
    # it would perform is fail-safe (refuse) rather than fail-open.
    FACT_ID_DEVIATION,
    FAIL_SAFE_MERGE_RULE,
    TRIAL_HISTORY_SUBJECT_RULE,
    UNPINNED_SOURCE_VERSION,
    ClaimRendering,
    DerivationEvent,
    DerivedClaimIdentity,
    EvidenceOccurrence,
    FactIdentityResolver,
    LocatorKind,
    PairsInput,
    Polarity,
    PropositionCoalescence,
    PropositionVersion,
    RefusedMerge,
    ScriptedFactIdentity,
    SpanLocator,
    UnresolvedFactIdentity,
    anchor_locator,
    char_range_locator,
    coalesce_propositions,
    derivation_event,
    derivation_event_id,
    derivation_id,
    derivation_ids_for_spans,
    evidence_occurrence,
    evidence_occurrence_id,
    evidence_occurrence_ids_for_spans,
    feedback_subject_id,
    identify,
    locators_for_spans,
    normalize_span_text,
    note_version_hash,
    proposition_version,
    proposition_version_id,
    text_hash,
)
from tessellum.dks.entity_registry import (
    # QP1 — canonical entities, reliable-kinds-only resolution, and the
    # O(N) authored relations seed (never a pair enumeration)
    ANY_OBJECT_TYPE,
    DEFAULT_DEFINING_CATEGORIES,
    DEFAULT_RELATION_FIELDS,
    EXCLUSION_ALIAS_KIND,
    RELIABLE_ALIAS_KINDS,
    AliasKind,
    AuthoredRelation,
    CandidateEntity,
    Entity,
    EntityAlias,
    EntityCandidateRef,
    EntityRegistry,
    LiteralObjectResolver,
    MentionRecord,
    NoteFacts,
    ObjectResolver,
    RegistrySink,
    RegistrySource,
    RelationFieldSpec,
    ResolutionIndex,
    SeedAudit,
    SpineSpec,
    UnreliableAliasError,
    aggregate_candidates,
    audit_authored_seed,
    candidate_id,
    link_candidates,
    norm,
    project_spine,
    registry_content_digest,
    relation_id,
)
from tessellum.dks.resolve_entity import (
    # QP1 — the tiered mention→entity resolver (exact → FTS → dense),
    # exclusion-aware at every tier, abstaining on ambiguity
    DEFAULT_SEARCH_LIMIT,
    DISAMBIGUATED_SCORE,
    EXACT_SCORE,
    FULL_TEXT_RELAXED_SCORE,
    FULL_TEXT_TYPED_SCORE,
    EntityResolver,
    EntitySearchBackend,
    EntitySearchHit,
    MappingSearchBackend,
    Resolution,
    ResolutionMethod,
    RetrievalSearchBackend,
    TypedObjectResolver,
)
from tessellum.dks.status import (
    # QP5 — computed status: `supersede` pre-filter, attack-only fixed
    # point, `support` post-classification. Never written, always derived.
    # The bare `status(claim)` query is deliberately NOT re-exported: the
    # name would shadow this submodule's own attribute on the package.
    # Reach it as `dks.status.status`, or use `StatusQuery` / `classify`.
    ATTACK,
    REVISE,
    STATUSES,
    SUPERSEDE,
    SUPPORT,
    ClaimStatus,
    ClaimView,
    EdgeExplanation,
    EdgeSet,
    EdgeSetSource,
    EdgeSetView,
    EdgeView,
    Explanation,
    ProvisionalStatusError,
    Status,
    StatusError,
    StatusQuery,
    StatusTable,
    UnknownClaimError,
    attack_pairs,
    classify,
    compute_statuses,
    edgeset_digest,
    explain,
    provisionally_warranted,
    superseded_claims,
    supported_claims,
)
from tessellum.dks.support_dependency import (
    # QP5's second half — the dependency validator that sits OUTSIDE the
    # labelling. `warranted` is a dialectical verdict; it admits a defeated
    # necessary premise and admits circular support. `is_grounded` answers
    # the other question, and `is_answerable` is the conjunction the answer
    # gate actually needs. Support kinds are declared through a port, not
    # by widening the append-only log. Its per-reason constants stay on
    # the submodule (`dks.support_dependency.REASON_CYCLIC_SUPPORT`, …),
    # as `memory_port`'s and `consolidation`'s already do.
    CONSERVATIVE_SUPPORT_KINDS,
    CONTRIBUTORY,
    EVIDENTIAL,
    NECESSARY,
    SUPPORT_KINDS,
    ConservativeSupportKinds,
    DeclaredSupportKinds,
    GroundingClaimView,
    GroundingTable,
    GroundingValidator,
    GroundingVerdict,
    SupportKind,
    SupportKindError,
    SupportKindResolver,
    grounding_digest,
    grounding_verdict,
    is_answerable,
    is_grounded,
    support_premises,
    validate_support_dependencies,
)
from tessellum.dks.memory_port import (
    # QP6 — the three-call protocol↔memory boundary: retrieve /
    # status+explain / append_batch, with the four-condition admission
    # gate and a snapshot-pinned read
    CLAIM_ELIGIBLE_BLOCKS,
    EVIDENCE_ONLY_BLOCKS,
    OPERATORS,
    ORIGIN_STALENESS,
    PROVENANCES,
    STALENESS_SECTION,
    AdmissionError,
    AdmissionVerdict,
    AppendOutcome,
    BuildingBlockEligibility,
    CandidateSource,
    ChainLink,
    ClaimCandidate,
    ClaimEligibility,
    ClaimLogReader,
    ClaimProposal,
    ClaimRow,
    EdgeProposal,
    EdgeRow,
    EpisodeMemory,
    LogAppendPort,
    MappingNoteSearch,
    MemoryMetrics,
    MemoryPort,
    MemoryPortError,
    MemorySnapshot,
    NoteHit,
    NoteSearch,
    Operator,
    Proposal,
    Provenance,
    RelationCandidate,
    RelationReader,
    RelationRow,
    RetrievalNoteSearch,
    RetrieveResult,
    StaleClaim,
    StatusLabeller,
    claim_content_id,
    edge_content_id,
    effect_for_proposal,
    grounded_status_labeller,
    text_content_hash,
)
from tessellum.dks.reach import (
    # QP7 — seeded traversal with a HARD hop budget; the bridge note a
    # ranker cannot rank, reached over the authored link graph
    AMBIGUOUS_SEED_WEIGHT,
    DEFAULT_LAMBDA_COST,
    DEFAULT_MAX_HOPS,
    DEFAULT_MAX_NOTES,
    DEFAULT_MAX_RERETRIEVALS,
    DEFAULT_SEED_K,
    HARD_MAX_HOPS,
    BudgetError,
    HopBudget,
    LinkExpansionBackend,
    MappingLinkBackend,
    MappingSimilarityBackend,
    MissingHop,
    ReachResult,
    ReachStopReason,
    ReachVia,
    ReachedNote,
    SeededReach,
    SimilarityBackend,
)
from tessellum.dks.memory_tiers import (
    # QP9 — Tier A / Tier B vocabulary, the η reliability gate, and the
    # DEMOTION-FIRST feedback rule (reinforcement is off by default)
    DEFAULT_FEEDBACK_POLICY,
    EVENT_KINDS,
    INITIAL_FEEDBACK_SCORE,
    NEGATIVE_VERDICTS,
    RELIABILITY_FLOOR,
    REPRESENTATIONS,
    RESOLVED_ORIGIN,
    SOURCE_EXPLICIT_THUMB,
    SOURCE_REVIEWED_QA,
    SUBJECT_KINDS,
    TIERS,
    VERDICTS,
    CachePrecisionComparison,
    CachedMapping,
    CorrectionFlag,
    EventKind,
    FeedbackEvent,
    FeedbackEventError,
    FeedbackPolicy,
    FeedbackSink,
    PrecisionProbe,
    QueryCacheSource,
    RepresentationName,
    RepresentationSpec,
    ResolvedRelation,
    ScoreAction,
    ScoreDecision,
    StaticVerdictSource,
    SubjectKind,
    TierName,
    TierSpec,
    TrialHistory,
    Verdict,
    VerdictOutcome,
    VerdictSource,
    compare_target_note_precision,
    correction_flags,
    has_open_correction,
    is_rebuildable_projection,
    meets_reliability_gate,
    open_correction_flags,
    pack_embedding,
    precision,
    query_key_for,
    reliability,
    score_after,
    tally_trials,
    unpack_embedding,
)
from tessellum.dks.query_protocol import (
    # QP8 — the query entry: consult memory, reach, name the relation,
    # derive with locators, refute, then decide THREE ways on status —
    # and `warranted` alone never answers: the support-dependency
    # validator must pass too. The abstain reasons, this phase's
    # `ABSTAIN_DEPENDENCY` included, stay on `dks.query_protocol`.
    DEFAULT_ABSTENTION_BOUND,
    DEFAULT_MEMORY_K,
    OUTCOMES,
    Chain,
    ChainStep,
    ClaimDeriver,
    DKSQueryCapability,
    Decision,
    DerivedClaim,
    DerivedClaimDraft,
    Grounding,
    GroundingPolicy,
    GroundingRecord,
    MemoryReadRecord,
    ModelBudget,
    OutcomeTally,
    QueryOutcome,
    QueryProtocol,
    QueryProtocolError,
    QueryRequest,
    QueryResult,
    RefutationOutcome,
    RefutationRecord,
    RelationNamer,
    RelationNaming,
    TableClaimDeriver,
    TableRelationNamer,
    ValidationPolicy,
    decide,
    derive_claim,
    refute,
    tally_outcomes,
)
from tessellum.dks.demotion import (
    # QP10 — the periodic re-derivation gate and its THREE triggers.
    # Suppress the claim, hand a FROZEN model only its cited sources,
    # compare arithmetically; demotion is an append, never a delete.
    # Re-derivation tests REPRODUCIBILITY, not truth, so the five
    # distinguished outcomes route to four dispositions — an inconclusive
    # signal quarantines or requests review instead of demoting.
    # `demotion.OUTCOMES` (the five outcome kinds) is deliberately NOT
    # re-exported: `OUTCOMES` at package level is already QP8's three
    # query decisions. Reach it as `dks.demotion.OUTCOMES`.
    ACTIONS,
    DEFAULT_DEMOTION_POLICY,
    DEFAULT_INTERVAL_DAYS,
    DISPOSITIONS,
    DISPOSITION_DEMOTE,
    DISPOSITION_HOLD,
    DISPOSITION_QUARANTINE,
    DISPOSITION_REQUEST_REVIEW,
    INDEPENDENCE_FLOOR,
    OUTCOME_FAILED_GENERALISATION,
    OUTCOME_FAILED_REPRODUCTION,
    OUTCOME_GROUNDING_FAILURE,
    OUTCOME_STALE_EVIDENCE,
    OUTCOME_SURVIVING_CONTRADICTION,
    REGENERATION_FLOOR,
    SOURCE_SUPPORT_FLOOR,
    STANDING_ENTRY_KINDS,
    TRIGGERS,
    TRIGGER_CONTRADICTION,
    TRIGGER_INDEPENDENCE_BELOW_FLOOR,
    TRIGGER_REDERIVATION_FAILURE,
    UNVERIFIABLE_FRESHNESS,
    WITHHOLDING_DISPOSITIONS,
    WITHHOLDING_ENTRY_KINDS,
    CitedSource,
    ClaimLabelSource,
    CurrentStatusSource,
    DemotionAction,
    DemotionEntry,
    DemotionError,
    DemotionLedger,
    DemotionOutcome,
    DemotionOutcomeKind,
    DemotionPolicy,
    DemotionReview,
    DemotionSweep,
    DemotionTrigger,
    Disposition,
    EvidenceFreshnessCheck,
    FrozenModelError,
    FrozenReDerivationModel,
    GateNotArmedError,
    IndependenceCheck,
    IndependenceSource,
    LedgerEntryKind,
    PromotedClaimRecord,
    PromotionRecordView,
    ReDerivationGate,
    ReDerivationModel,
    ReDerivationOutput,
    ReDerivationRequest,
    RecoveryError,
    RecoveryOutcome,
    RegenerationCheck,
    ScriptedReDerivationModel,
    SourceReader,
    StaticIndependenceSource,
    StaticSourceReader,
    StaticStatusSource,
    StatusFlipCheck,
    SuppressionError,
    TrialEventView,
    VerdictQuery,
    VerdictQueryStatusSource,
    agreement,
    as_capability_result,
    build_request,
    check_evidence_freshness,
    check_independence,
    check_regeneration,
    check_status_flip,
    claim_label,
    classify_outcomes,
    due_records,
    entry_for_review,
    independence_from_events,
    recover,
    recovery_capability_result,
    recovery_proposals,
    require_armed,
    require_frozen,
    require_suppression,
    retraction_proposals,
    source_support,
    strongest_action,
    strongest_disposition,
)
from tessellum.dks.consolidation import (
    # QP12 — gate (ii), the reviewed promotion batch. Ships REFUSING to
    # run: promotion is off by default, the promotion A/B is unrun, and
    # sign-off must be requested with use_human=True. The independence
    # term counts ORIGIN-distinct contexts, not episode ids — a claim
    # promoted by this system carries its origin forward, so restating
    # it never corroborates it.
    AUTHORED_ORIGIN,
    BUILD_NOISE_FLOOR,
    CONDITIONS,
    DEFAULT_CONSOLIDATION_POLICY,
    DEFAULT_DWELL_DAYS,
    DEFAULT_PRIOR_ART_TOP_K,
    DEFAULT_SYNONYMY_TAU,
    DWELL_WINDOW_DAYS_MAX,
    DWELL_WINDOW_DAYS_MIN,
    ENTAILMENT_CALIBRATION_CAVEAT,
    HARD_CONDITIONS,
    INDEPENDENCE_BASIS_EPISODES,
    INDEPENDENCE_BASIS_FACTS,
    INDEPENDENCE_ORIGIN_RULE,
    MIN_AB_ORDERINGS,
    MIN_AB_RUNS_PER_ARM,
    MIN_INDEPENDENT_CONTEXTS,
    MIN_RECURRENCE,
    ORIGIN_KINDS,
    ORIGIN_PROVENANCES,
    PROMOTION_ENABLED_BY_DEFAULT,
    PROMOTION_TARGETS,
    PROVENANCE_CONSTRUCTED,
    PROVENANCE_LOCATED,
    QUALIFIER_KINDS,
    REQUIRED_REGRESSION_CLASSES,
    UNRUN_PROMOTION_AB,
    AdditiveProseAuthor,
    AuthorityCapError,
    ClaimOrigin,
    ConditionName,
    ConditionOutcome,
    ConsolidationBatch,
    ConsolidationDisabledError,
    ConsolidationError,
    ConsolidationPolicy,
    DedupAction,
    DedupDecision,
    DedupJudge,
    DedupRequest,
    DemotionHandle,
    DerivationOccurrence,
    EntailmentJudge,
    EntailmentRequest,
    EntailmentVerdict,
    HumanGateError,
    HumanReviewRequest,
    IndependenceMeasurement,
    LinkBeforeCreateJudge,
    MoverIsJudgeError,
    OriginKind,
    PriorArtEntry,
    PriorArtIndex,
    PriorArtMatch,
    PromotionABGate,
    PromotionABNotRunError,
    PromotionCandidate,
    PromotionDiff,
    PromotionLifecycle,
    PromotionProseAuthor,
    PromotionRecord,
    PromotionTarget,
    PromotionVerdict,
    ProseRequest,
    Qualifier,
    QualifierKind,
    QualifierStrippedError,
    StaticEntailmentJudge,
    StaticPriorArtIndex,
    UncalibratedEntailmentJudge,
    corpus_origin,
    effects_for_promotion,
    evaluate_candidate,
    evaluate_dedup,
    evaluate_grounding,
    evaluate_independence,
    evaluate_recurrence,
    evaluate_reliability,
    evaluate_renderable,
    evaluate_stability,
    independence_count,
    independence_measurement,
    lifecycle_for,
    missing_locators,
    missing_qualifiers,
    origin_after_promotion,
    prior_art_shortlist,
    require_authority,
    require_human_sign_off,
    require_independent_reviewer,
    require_promotion_enabled,
    run_consolidation_batch,
    self_authored_origin,
    verify_qualifiers_intact,
)
from tessellum.dks.meta import (
    # Meta-DKS (schema-mutation runtime)
    Attacker,
    DEFAULT_MIN_CYCLES,
    HeuristicProposer,
    LLMAttacker,
    LLMProposer,
    META_ATTACK_KIND,
    META_SCHEMA,
    MetaCounterArgument,
    MetaCycle,
    MetaCycleResult,
    MetaEdgeType,
    MetaObservation,
    NoOpAttacker,
    Proposer,
    SchemaEditProposal,
    SCHEMA_EDIT_PROPOSAL_KIND,
    SURVIVE_THRESHOLD,
    load_event_log,
    write_event_log,
)


__all__ = [
    # Types
    "ToulminComponent",
    "CycleMode",
    "CounterStrength",
    "WarrantChangeKind",
    # Dataclasses
    "DKSObservation",
    "DKSWarrant",
    "DKSArgument",
    "DKSContradicts",
    "DKSCounterArgument",
    "DKSPattern",
    "DKSRuleRevision",
    "DKSCycleResult",
    "WarrantChange",
    "DKSRunResult",
    # Allocator
    "allocate_cycle_fz",
    # Provenance (P1)
    "temporal_holdout_valid",
    # Seam (P2)
    "Capability",
    "CapabilityEffect",
    "CapabilityResult",
    "DKSCandidate",
    "DKSExecutor",
    "adapt_cycle_result",
    "adapt_run_result",
    # Compiler (P3)
    "DKSNoteCompiler",
    # Validation (P4)
    "ClaimType",
    "ClaimTypeRouter",
    "classify_claim",
    "temporal_holdout_scorer",
    "validate_claims",
    # Autonomy (P5)
    "EpistemicObligation",
    "InquiryFrontier",
    "StopDecision",
    "voi_stop_decision",
    "run_bounded_inquiry",
    "AuthorityLadder",
    "AuthorityLadderError",
    # Ontology reform (P6)
    "BBContract",
    "AcceptanceVerdict",
    "acceptance_from_labelling",
    "InquiryMove",
    "DKS_MOVE_ALGEBRA",
    "plan_move",
    # Self-driving elevation (P7)
    "MaturityProfile",
    "DeepUnderstandingCertificate",
    "CertificateError",
    "issue_certificate",
    "revoke",
    "QuestionValue",
    "rank_questions",
    "RewardInputs",
    "move_reward",
    "MoveRanker",
    "RankerAuthorityError",
    # Runtime
    "DKSCycle",
    "DKSRunner",
    # Helpers
    "aggregate_warrant_changes",
    # P-side retrieval
    "RetrievalClient",
    "RetrievalHit",
    "LinkNeighbour",
    "MAX_EXPANSION_HOPS",
    "DEFAULT_EXPANSION_K",
    # FSM dispatcher over the BB schema
    "BBPath",
    "BBPathStep",
    "DKSStateMachine",
    "TransitionHandler",
    # Dung AF
    "DungAF",
    "DungLabel",
    "grounded_extension",
    "grounded_labelling",
    # Confidence gating
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DKSConfidenceModel",
    "ConstantConfidence",
    "EscalationDecision",
    "decide_escalation",
    # Learned confidence + calibration
    "DEFAULT_RECENCY_HALFLIFE_CYCLES",
    "DEFAULT_TARGET_FALSE_GATE_RATE",
    "CalibratedConfidence",
    "CalibrationResult",
    "calibrate_from_traces",
    # Warrant persistence
    "WarrantRegistry",
    "WarrantHistory",
    "HistoryEntry",
    "load_warrants_from_vault",
    # Meta-DKS (schema-mutation runtime)
    "DEFAULT_MIN_CYCLES",
    "META_SCHEMA",
    "MetaCycle",
    "MetaCycleResult",
    "MetaEdgeType",
    "MetaObservation",
    "Proposer",
    "HeuristicProposer",
    "LLMProposer",
    # Attacker
    "Attacker",
    "NoOpAttacker",
    "LLMAttacker",
    "MetaCounterArgument",
    "META_ATTACK_KIND",
    "SURVIVE_THRESHOLD",
    "SchemaEditProposal",
    "SCHEMA_EDIT_PROPOSAL_KIND",
    "load_event_log",
    "write_event_log",
    # Query-time protocol (QP0) — the three derived-claim identities
    "FACT_ID_DEVIATION",
    "FAIL_SAFE_MERGE_RULE",
    "TRIAL_HISTORY_SUBJECT_RULE",
    "UNPINNED_SOURCE_VERSION",
    "ClaimRendering",
    "DerivationEvent",
    "DerivedClaimIdentity",
    "EvidenceOccurrence",
    "FactIdentityResolver",
    "LocatorKind",
    "PairsInput",
    "Polarity",
    "PropositionCoalescence",
    "PropositionVersion",
    "RefusedMerge",
    "ScriptedFactIdentity",
    "SpanLocator",
    "UnresolvedFactIdentity",
    "anchor_locator",
    "char_range_locator",
    "coalesce_propositions",
    "derivation_event",
    "derivation_event_id",
    "derivation_id",
    "derivation_ids_for_spans",
    "evidence_occurrence",
    "evidence_occurrence_id",
    "evidence_occurrence_ids_for_spans",
    "feedback_subject_id",
    "identify",
    "locators_for_spans",
    "normalize_span_text",
    "note_version_hash",
    "proposition_version",
    "proposition_version_id",
    "text_hash",
    # QP1 — entity registry + the O(N) authored relations seed
    "ANY_OBJECT_TYPE",
    "DEFAULT_DEFINING_CATEGORIES",
    "DEFAULT_RELATION_FIELDS",
    "EXCLUSION_ALIAS_KIND",
    "RELIABLE_ALIAS_KINDS",
    "AliasKind",
    "AuthoredRelation",
    "CandidateEntity",
    "Entity",
    "EntityAlias",
    "EntityCandidateRef",
    "EntityRegistry",
    "LiteralObjectResolver",
    "MentionRecord",
    "NoteFacts",
    "ObjectResolver",
    "RegistrySink",
    "RegistrySource",
    "RelationFieldSpec",
    "ResolutionIndex",
    "SeedAudit",
    "SpineSpec",
    "UnreliableAliasError",
    "aggregate_candidates",
    "audit_authored_seed",
    "candidate_id",
    "link_candidates",
    "norm",
    "project_spine",
    "registry_content_digest",
    "relation_id",
    # QP1 — the tiered mention→entity resolver
    "DEFAULT_SEARCH_LIMIT",
    "DISAMBIGUATED_SCORE",
    "EXACT_SCORE",
    "FULL_TEXT_RELAXED_SCORE",
    "FULL_TEXT_TYPED_SCORE",
    "EntityResolver",
    "EntitySearchBackend",
    "EntitySearchHit",
    "MappingSearchBackend",
    "Resolution",
    "ResolutionMethod",
    "RetrievalSearchBackend",
    "TypedObjectResolver",
    # QP5 — computed status (bare `status` stays on the submodule)
    "ATTACK",
    "REVISE",
    "STATUSES",
    "SUPERSEDE",
    "SUPPORT",
    "ClaimStatus",
    "ClaimView",
    "EdgeExplanation",
    "EdgeSet",
    "EdgeSetSource",
    "EdgeSetView",
    "EdgeView",
    "Explanation",
    "ProvisionalStatusError",
    "Status",
    "StatusError",
    "StatusQuery",
    "StatusTable",
    "UnknownClaimError",
    "attack_pairs",
    "classify",
    "compute_statuses",
    "edgeset_digest",
    "explain",
    "provisionally_warranted",
    "superseded_claims",
    "supported_claims",
    # QP5's second half — the support-dependency validator, outside the
    # labelling: `warranted` AND `is_grounded`, i.e. `is_answerable`
    "CONSERVATIVE_SUPPORT_KINDS",
    "CONTRIBUTORY",
    "EVIDENTIAL",
    "NECESSARY",
    "SUPPORT_KINDS",
    "ConservativeSupportKinds",
    # (`REASON_*` diagnoses stay on `dks.support_dependency`.)
    "DeclaredSupportKinds",
    "GroundingClaimView",
    "GroundingTable",
    "GroundingValidator",
    "GroundingVerdict",
    "SupportKind",
    "SupportKindError",
    "SupportKindResolver",
    "grounding_digest",
    "grounding_verdict",
    "is_answerable",
    "is_grounded",
    "support_premises",
    "validate_support_dependencies",
    # QP6 — the three-call protocol↔memory boundary
    "CLAIM_ELIGIBLE_BLOCKS",
    "EVIDENCE_ONLY_BLOCKS",
    "OPERATORS",
    "ORIGIN_STALENESS",
    "PROVENANCES",
    "STALENESS_SECTION",
    "AdmissionError",
    "AdmissionVerdict",
    "AppendOutcome",
    "BuildingBlockEligibility",
    "CandidateSource",
    "ChainLink",
    "ClaimCandidate",
    "ClaimEligibility",
    "ClaimLogReader",
    "ClaimProposal",
    "ClaimRow",
    "EdgeProposal",
    "EdgeRow",
    "EpisodeMemory",
    "LogAppendPort",
    "MappingNoteSearch",
    "MemoryMetrics",
    "MemoryPort",
    "MemoryPortError",
    "MemorySnapshot",
    "NoteHit",
    "NoteSearch",
    "Operator",
    "Proposal",
    "Provenance",
    "RelationCandidate",
    "RelationReader",
    "RelationRow",
    "RetrievalNoteSearch",
    "RetrieveResult",
    "StaleClaim",
    "StatusLabeller",
    "claim_content_id",
    "edge_content_id",
    "effect_for_proposal",
    "grounded_status_labeller",
    "text_content_hash",
    # QP7 — seeded traversal under a hard hop budget
    "AMBIGUOUS_SEED_WEIGHT",
    "DEFAULT_LAMBDA_COST",
    "DEFAULT_MAX_HOPS",
    "DEFAULT_MAX_NOTES",
    "DEFAULT_MAX_RERETRIEVALS",
    "DEFAULT_SEED_K",
    "HARD_MAX_HOPS",
    "BudgetError",
    "HopBudget",
    "LinkExpansionBackend",
    "MappingLinkBackend",
    "MappingSimilarityBackend",
    "MissingHop",
    "ReachResult",
    "ReachStopReason",
    "ReachVia",
    "ReachedNote",
    "SeededReach",
    "SimilarityBackend",
    # QP9 — Tier A / Tier B + the demotion-first feedback rule
    "DEFAULT_FEEDBACK_POLICY",
    "EVENT_KINDS",
    "INITIAL_FEEDBACK_SCORE",
    "NEGATIVE_VERDICTS",
    "RELIABILITY_FLOOR",
    "REPRESENTATIONS",
    "RESOLVED_ORIGIN",
    "SOURCE_EXPLICIT_THUMB",
    "SOURCE_REVIEWED_QA",
    "SUBJECT_KINDS",
    "TIERS",
    "VERDICTS",
    "CachePrecisionComparison",
    "CachedMapping",
    "CorrectionFlag",
    "EventKind",
    "FeedbackEvent",
    "FeedbackEventError",
    "FeedbackPolicy",
    "FeedbackSink",
    "PrecisionProbe",
    "QueryCacheSource",
    "RepresentationName",
    "RepresentationSpec",
    "ResolvedRelation",
    "ScoreAction",
    "ScoreDecision",
    "StaticVerdictSource",
    "SubjectKind",
    "TierName",
    "TierSpec",
    "TrialHistory",
    "Verdict",
    "VerdictOutcome",
    "VerdictSource",
    "compare_target_note_precision",
    "correction_flags",
    "has_open_correction",
    "is_rebuildable_projection",
    "meets_reliability_gate",
    "open_correction_flags",
    "pack_embedding",
    "precision",
    "query_key_for",
    "reliability",
    "score_after",
    "tally_trials",
    "unpack_embedding",
    # QP8 — the query entry and its three-way decision
    # (`ABSTAIN_*` reasons stay on `dks.query_protocol`.)
    "DEFAULT_ABSTENTION_BOUND",
    "DEFAULT_MEMORY_K",
    "OUTCOMES",
    "Chain",
    "ChainStep",
    "ClaimDeriver",
    "DKSQueryCapability",
    "Decision",
    "DerivedClaim",
    "DerivedClaimDraft",
    "Grounding",
    "GroundingPolicy",
    "GroundingRecord",
    "MemoryReadRecord",
    "ModelBudget",
    "OutcomeTally",
    "QueryOutcome",
    "QueryProtocol",
    "QueryProtocolError",
    "QueryRequest",
    "QueryResult",
    "RefutationOutcome",
    "RefutationRecord",
    "RelationNamer",
    "RelationNaming",
    "TableClaimDeriver",
    "TableRelationNamer",
    "ValidationPolicy",
    "decide",
    "derive_claim",
    "refute",
    "tally_outcomes",
    # QP10 — the re-derivation gate: three triggers, FIVE distinguished
    # outcomes, four dispositions. `demotion.OUTCOMES` is not flattened
    # up here — `OUTCOMES` is QP8's; reach it as `dks.demotion.OUTCOMES`
    "ACTIONS",
    "DEFAULT_DEMOTION_POLICY",
    "DEFAULT_INTERVAL_DAYS",
    "DISPOSITIONS",
    "DISPOSITION_DEMOTE",
    "DISPOSITION_HOLD",
    "DISPOSITION_QUARANTINE",
    "DISPOSITION_REQUEST_REVIEW",
    "INDEPENDENCE_FLOOR",
    "OUTCOME_FAILED_GENERALISATION",
    "OUTCOME_FAILED_REPRODUCTION",
    "OUTCOME_GROUNDING_FAILURE",
    "OUTCOME_STALE_EVIDENCE",
    "OUTCOME_SURVIVING_CONTRADICTION",
    "REGENERATION_FLOOR",
    "SOURCE_SUPPORT_FLOOR",
    "STANDING_ENTRY_KINDS",
    "TRIGGERS",
    "TRIGGER_CONTRADICTION",
    "TRIGGER_INDEPENDENCE_BELOW_FLOOR",
    "TRIGGER_REDERIVATION_FAILURE",
    "UNVERIFIABLE_FRESHNESS",
    "WITHHOLDING_DISPOSITIONS",
    "WITHHOLDING_ENTRY_KINDS",
    "CitedSource",
    "ClaimLabelSource",
    "CurrentStatusSource",
    "DemotionAction",
    "DemotionEntry",
    "DemotionError",
    "DemotionLedger",
    "DemotionOutcome",
    "DemotionOutcomeKind",
    "DemotionPolicy",
    "DemotionReview",
    "DemotionSweep",
    "DemotionTrigger",
    "Disposition",
    "EvidenceFreshnessCheck",
    "FrozenModelError",
    "FrozenReDerivationModel",
    "GateNotArmedError",
    "IndependenceCheck",
    "IndependenceSource",
    "LedgerEntryKind",
    "PromotedClaimRecord",
    "PromotionRecordView",
    "ReDerivationGate",
    "ReDerivationModel",
    "ReDerivationOutput",
    "ReDerivationRequest",
    "RecoveryError",
    "RecoveryOutcome",
    "RegenerationCheck",
    "ScriptedReDerivationModel",
    "SourceReader",
    "StaticIndependenceSource",
    "StaticSourceReader",
    "StaticStatusSource",
    "StatusFlipCheck",
    "SuppressionError",
    "TrialEventView",
    "VerdictQuery",
    "VerdictQueryStatusSource",
    "agreement",
    "as_capability_result",
    "build_request",
    "check_evidence_freshness",
    "check_independence",
    "check_regeneration",
    "check_status_flip",
    "claim_label",
    "classify_outcomes",
    "due_records",
    "entry_for_review",
    "independence_from_events",
    "recover",
    "recovery_capability_result",
    "recovery_proposals",
    "require_armed",
    "require_frozen",
    "require_suppression",
    "retraction_proposals",
    "source_support",
    "strongest_action",
    "strongest_disposition",
    # QP12 — the reviewed promotion batch (ships refusing to run), with
    # the independence term counted over ORIGIN-distinct contexts
    "AUTHORED_ORIGIN",
    "BUILD_NOISE_FLOOR",
    "CONDITIONS",
    "DEFAULT_CONSOLIDATION_POLICY",
    "DEFAULT_DWELL_DAYS",
    "DEFAULT_PRIOR_ART_TOP_K",
    "DEFAULT_SYNONYMY_TAU",
    "DWELL_WINDOW_DAYS_MAX",
    "DWELL_WINDOW_DAYS_MIN",
    "ENTAILMENT_CALIBRATION_CAVEAT",
    "HARD_CONDITIONS",
    "INDEPENDENCE_BASIS_EPISODES",
    "INDEPENDENCE_BASIS_FACTS",
    "INDEPENDENCE_ORIGIN_RULE",
    "MIN_AB_ORDERINGS",
    "MIN_AB_RUNS_PER_ARM",
    "MIN_INDEPENDENT_CONTEXTS",
    "MIN_RECURRENCE",
    "ORIGIN_KINDS",
    "ORIGIN_PROVENANCES",
    "PROMOTION_ENABLED_BY_DEFAULT",
    "PROMOTION_TARGETS",
    "PROVENANCE_CONSTRUCTED",
    "PROVENANCE_LOCATED",
    "QUALIFIER_KINDS",
    "REQUIRED_REGRESSION_CLASSES",
    "UNRUN_PROMOTION_AB",
    "AdditiveProseAuthor",
    "AuthorityCapError",
    "ClaimOrigin",
    "ConditionName",
    "ConditionOutcome",
    "ConsolidationBatch",
    "ConsolidationDisabledError",
    "ConsolidationError",
    "ConsolidationPolicy",
    "DedupAction",
    "DedupDecision",
    "DedupJudge",
    "DedupRequest",
    "DemotionHandle",
    "DerivationOccurrence",
    "EntailmentJudge",
    "EntailmentRequest",
    "EntailmentVerdict",
    "HumanGateError",
    "HumanReviewRequest",
    "IndependenceMeasurement",
    "LinkBeforeCreateJudge",
    "MoverIsJudgeError",
    "OriginKind",
    "PriorArtEntry",
    "PriorArtIndex",
    "PriorArtMatch",
    "PromotionABGate",
    "PromotionABNotRunError",
    "PromotionCandidate",
    "PromotionDiff",
    "PromotionLifecycle",
    "PromotionProseAuthor",
    "PromotionRecord",
    "PromotionTarget",
    "PromotionVerdict",
    "ProseRequest",
    "Qualifier",
    "QualifierKind",
    "QualifierStrippedError",
    "StaticEntailmentJudge",
    "StaticPriorArtIndex",
    "UncalibratedEntailmentJudge",
    "corpus_origin",
    "effects_for_promotion",
    "evaluate_candidate",
    "evaluate_dedup",
    "evaluate_grounding",
    "evaluate_independence",
    "evaluate_recurrence",
    "evaluate_reliability",
    "evaluate_renderable",
    "evaluate_stability",
    "independence_count",
    "independence_measurement",
    "lifecycle_for",
    "missing_locators",
    "missing_qualifiers",
    "origin_after_promotion",
    "prior_art_shortlist",
    "require_authority",
    "require_human_sign_off",
    "require_independent_reviewer",
    "require_promotion_enabled",
    "run_consolidation_batch",
    "self_authored_origin",
    "verify_qualifiers_intact",
]
