"""Single source of version + status. Imported by ``tessellum.__init__`` and
``tessellum.cli`` so neither holds its own copy."""

__version__ = "0.0.58"

__status__ = (
    "alpha — Phase IV of plan_v01_completion_roadmap: capture-side "
    "helper skills + skill catalog cleanup.\n"
    "\n"
    "Key contributions:\n"
    " • Two new capture-side skills ported from AbuseSlipBox + adapted: "
    "tessellum-classify-content (5-step BB classification — segments "
    "content by topic boundaries, labels each segment with one of the "
    "8 BB types + content domain; pure analysis, no vault writes) and "
    "tessellum-route-content (6-step routing with 3-criterion "
    "sub-category novelty framework — source / operational task / "
    "maintenance — that decides existing-vs-new sub-category for each "
    "classified segment). Both ship with Composer-pipeline sidecars.\n"
    " • Skill catalog rewritten from scratch — entry_skill_catalog.md "
    "previously listed 84 AbuseSlipBox skills (copied wholesale from "
    "AB seed) that don't exist in Tessellum. Replaced with an honest "
    "13-skill catalog organised into 5 clusters: DKS runtime, "
    "capture-side helpers, search & answer, trail management, "
    "maintenance & format. Each row maps a 'I want to...' user intent "
    "to a real Tessellum skill canonical.\n"
    " • Sub-Category Novelty Framework is the load-bearing idea — 3 "
    "criteria (source / operational task / maintenance) with a 0-3 "
    "novel-count decision rule (0-1 → existing, 1 emits drift "
    "warning, 2-3 → new). Generalises AB's vault-specific routing "
    "patterns into a vault-agnostic decision procedure.\n"
    "\n"
    "Seed manifest extended with 4 new entries (2 canonicals + 2 "
    "sidecars). 871 tests pass (unchanged from v0.0.57)."
)
