"""Single source of package version and current capability status."""

__version__ = "1.13.0"

__status__ = (
    "Current main - Composer v4 dynamic workflows, the P0-P9 knowledge-transaction "
    "track, multi-document corpus digestion, the v5 automatic runtime, the "
    "DKS P1-P7 self-driving reasoning arc, and a golden-eval-hardened digestion "
    "pipeline (P16-P24), carried through the J3 grounded-context arc: scoped source delivery, a default-ON identifier grounding gate, and the projection law.\n"
    "\n"
    "Tessellum provides typed Composer pipelines, durable verified resume, the "
    "P0-P9 snapshot-pinned knowledge-transaction track (typed intents, staging "
    "overlay, exact write closure, structural + calibrated semantic gates, bounded "
    "planner loop, versioned atomic publication), a dialectic reasoning engine now "
    "carrying a provenance floor, a runtime capability seam, deterministic note "
    "compilation onto the transaction substrate, independent conformal validation, "
    "a bounded autonomy loop, a four-axis ontology, and validator-issued elevation, "
    "hybrid retrieval, a 12-command CLI, a 12-tool MCP server, and supervised "
    "eight-lane inbox digestion with durable jobs, leases, bounded retries, "
    "cancellation, atomic index publication, and source acknowledgement. Corpus "
    "digestion takes a whole set of documents into one coordinated planning run, "
    "decomposing a large corpus into a master plan plus dependency-ordered "
    "sub-plans that each promote as their own transaction. The calibrated grounding "
    "certificate now runs end to end — a reference scorer, claim extraction, the "
    "grounding-verifier seam, and an A7.5 go/no-go gate — and its production judge "
    "is now the system's own LLM backend, leaving a labelled corpus as the one "
    "external prerequisite. Hybrid retrieval (BM25 + dense, RRF-fused) runs end to "
    "end on the live index — feeding reference context to the writer and "
    "auto-generating each note's relevance-ranked ## References graph edges. Note "
    "atomicity (density / one building block / full coverage) is enforced by a hard "
    "plan gate, and the runtime commit re-indexes only changed notes (incremental, "
    "proven equal to a full rebuild), and each digestion writer is handed its "
    "note-type's required-section contract, resolved by flavor. A golden-set "
    "end-to-end eval of the digestion pipeline drove the P16-P24 reliability "
    "remediation and, across nineteen scored runtime runs, the grounded-context "
    "arc: writers receive their verbatim owned source slices, planners and "
    "reviewers the code-computed ledger, and routing a retrieval-backed vault "
    "context plus a directory-landscape scan; a default-ON deterministic "
    "identifier-grounding gate blocks fabricated identifiers at write time; "
    "derivable plan content is code-generated so fabricated tallies have "
    "nowhere to live; the execute-only resume requires an acceptance stamp; "
    "checkpoint-resume picks up paid phases at claim; and a task-manager "
    "control plane observes, force-kills, and reaps leases. The eval gained a "
    "per-note-scoped dual-context judge, availability-scaled cross-reference "
    "scoring, and conformal grounding calibration; the gauntlet run scored "
    "Tier-2 0.926 and Tier-3 98.9%. Suite: 2212 passing.\n"
    "\n"
    "See CHANGELOG.md and docs/ for release details and engineering reference."
)
