"""Single source of version + status. Imported by ``tessellum.__init__`` and
``tessellum.cli`` so neither holds its own copy."""

__version__ = "0.0.59"

__status__ = (
    "alpha — Phase V of plan_v01_completion_roadmap: MCP server + "
    "how-to library.\n"
    "\n"
    "Key contributions:\n"
    " • Tessellum MCP server (tessellum/mcp/) — exposes the runtime "
    "as 7 MCP tools (search, format-check, bb-audit, fz-traverse, "
    "capture, list-skills, get-skill). Two-tier interaction model: "
    "deterministic Python-API wrappers (search/audit/etc.) PLUS "
    "skill-canonical retrieval (calling agent applies the procedure "
    "in its own LLM context). Stdio transport via the official mcp "
    "SDK. New `tessellum mcp serve` CLI subcommand integrates with "
    "Claude Desktop and any MCP-compatible host.\n"
    " • Three new how-to guides — howto_note_format walks through the "
    "YAML frontmatter spec (7 required fields + the v0.0.55 "
    "bb_schema_version + the v0.0.55 argument_perspective); "
    "howto_agent_integration documents the three invocation paths "
    "(MCP / Composer pipeline / Python API) with a decision rule for "
    "picking between them; howto_growing_a_trail walks through FZ "
    "trail authoring — manual + DKS-cycle-driven extension.\n"
    "\n"
    "15 new MCP smoke tests cover dispatch + tool implementations. "
    "Three new how-tos added to the seed manifest. 886 tests pass "
    "(+15 from v0.0.58)."
)
